language: php
php:
  - 5.3
  - 5.4

install:
  - git reset --hard
  - git clean -dxf
  - sudo apt-get update > /dev/null
  - sudo apt-get install php5-curl virtualbox > /dev/null
  - gem install vagrant
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bin/make-install-profile client_xyz xyz_foobar "Web app ABC" "Client XYZ's ABC app enables users to browse a database of records."

script: bin/run
